### PR TITLE
Fix memory leak when UnsubscribePacket is reused

### PR DESCRIPTION
**Pull request by sfod**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by xiazhvera — APPROVED** [review]

**Review by bretambrose — COMMENTED** [review]
I feel like there may be larger issues.  What happens when an  Unsubscribe gets submitted by multiple threads.  (Unsafely) Caching ephemeral data on the packet right before we submit to the native client feels broken.

**Comment by sfod** [comment]
> Caching ephemeral data on the packet right before we submit to the native client feels broken.

Unfortunately, the existing API of the `UnsubscribePacket` doesn't give much options on how to fix this issue:

```c++
bool initializeRawOptions(aws_mqtt5_packet_unsubscribe_view &raw_options) noexcept;
```

I wanted to introduce new class and method, something like this:

```c++

// Cleans up unsubscribeView on destruction.
class AwsMqtt5PacketUnsubscribeView_WrapperRAII {
    // ctor and dtor with RAII

    aws_mqtt5_packet_unsubscribe_view unsubscribeView;
};

AwsMqtt5PacketUnsubscribeView_WrapperRAII UnsubscribePacket::getRawOptions() noexcept;
```

, then the calling code would look like this:

```c++
bool Mqtt5ClientCore::Unsubscribe()
{
    ... 
    auto unsubscribeViewWrapper = unsubscribePacket->getRawOptions();
    int result = aws_mqtt5_client_unsubscribe(m_client, &unsubscribeViewWrapper.unsubscribeView, &options);
    return result;
}
```

But it'll be backward-incompatible change for `UnsubscribePacket`.

**Comment by bretambrose** [comment]
Why not ditch (ignore initializeFromRawOptions) and use something new instead?

**Comment by sfod** [comment]
`initializeFromRawOptions` has to remain valid, and it depends on the "cached" data inside the `UnsubscribePacket`, so we can't remove these fields, right?
Having two independent methods performing the same logic by two different ways feels wrong.

**Pull request merged**
